ALTER TABLE  sample_staff.invoice_partition
	PARTITION BY LIST  (department_code) (
    
	PARTITION MKT VALUES IN ('MKT'),
    PARTITION PROD VALUES IN ('PRD'),
    PARTITION RES VALUES IN ('RES'),
    PARTITION HR VALUES IN ('HR'),
    PARTITION DEV VALUES IN ('DEV'),
    PARTITION QA VALUES IN ('QA'),
    PARTITION CS VALUES IN ('CS'),
    PARTITION SAL VALUES IN ('SAL'),
    PARTITION FIN VALUES IN ('FIN')
    );